vmm: default GDB to false when deserializing
upstream commit: f346687e3d0426b45645a63f215fe9d0c4e79202

This fixes the valid VM config unit tests, which would otherwise fail
to deserialize their expected JSON config due to the missing "gdb" field.

The following unit test failures:

running 16 tests
test unit_tests::test_valid_vm_config_cpus ... FAILED
test unit_tests::test_valid_vm_config_devices ... FAILED
test unit_tests::test_valid_vm_config_memory ... FAILED
test unit_tests::test_valid_vm_config_fs ... FAILED
test unit_tests::test_valid_vm_config_kernel ... FAILED
test unit_tests::test_valid_vm_config_default ... FAILED
test unit_tests::test_valid_vm_config_cmdline ... FAILED
test unit_tests::test_valid_vm_config_pmem ... FAILED
test unit_tests::test_valid_vm_config_rng ... FAILED
test unit_tests::test_valid_vm_config_serial_pty_console_pty ... FAILED
test unit_tests::test_valid_vm_config_net ... FAILED
test unit_tests::test_valid_vm_config_serial_console ... FAILED
test unit_tests::test_valid_vm_config_disks ... FAILED
test unit_tests::test_valid_vm_config_tpm_socket ... FAILED
test unit_tests::test_valid_vm_config_vdpa ... FAILED
test unit_tests::test_valid_vm_config_vsock ... FAILED

failures:

---- unit_tests::test_valid_vm_config_cpus stdout ----
thread 'unit_tests::test_valid_vm_config_cpus' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `gdb`", line: 4, column: 17)', src/main.rs:960:73

---- unit_tests::test_valid_vm_config_devices stdout ----
thread 'unit_tests::test_valid_vm_config_devices' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `gdb`", line: 7, column: 17)', src/main.rs:960:73

---- unit_tests::test_valid_vm_config_memory stdout ----
thread 'unit_tests::test_valid_vm_config_memory' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `gdb`", line: 4, column: 17)', src/main.rs:960:73

---- unit_tests::test_valid_vm_config_fs stdout ----
thread 'unit_tests::test_valid_vm_config_fs' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `gdb`", line: 8, column: 17)', src/main.rs:960:73

---- unit_tests::test_valid_vm_config_kernel stdout ----
thread 'unit_tests::test_valid_vm_config_kernel' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `gdb`", line: 3, column: 13)', src/main.rs:960:73

---- unit_tests::test_valid_vm_config_default stdout ----
thread 'unit_tests::test_valid_vm_config_default' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `gdb`", line: 1, column: 44)', src/main.rs:960:73
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- unit_tests::test_valid_vm_config_cmdline stdout ----
thread 'unit_tests::test_valid_vm_config_cmdline' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `gdb`", line: 3, column: 13)', src/main.rs:960:73

---- unit_tests::test_valid_vm_config_pmem stdout ----
thread 'unit_tests::test_valid_vm_config_pmem' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `gdb`", line: 7, column: 17)', src/main.rs:960:73

---- unit_tests::test_valid_vm_config_rng stdout ----
thread 'unit_tests::test_valid_vm_config_rng' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `gdb`", line: 4, column: 13)', src/main.rs:960:73

---- unit_tests::test_valid_vm_config_serial_pty_console_pty stdout ----
thread 'unit_tests::test_valid_vm_config_serial_pty_console_pty' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `gdb`", line: 5, column: 17)', src/main.rs:960:73

---- unit_tests::test_valid_vm_config_net stdout ----
thread 'unit_tests::test_valid_vm_config_net' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `gdb`", line: 4, column: 17)', src/main.rs:960:73

---- unit_tests::test_valid_vm_config_serial_console stdout ----
thread 'unit_tests::test_valid_vm_config_serial_console' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `gdb`", line: 5, column: 17)', src/main.rs:960:73

---- unit_tests::test_valid_vm_config_disks stdout ----
thread 'unit_tests::test_valid_vm_config_disks' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `gdb`", line: 7, column: 17)', src/main.rs:960:73

---- unit_tests::test_valid_vm_config_tpm_socket stdout ----
thread 'unit_tests::test_valid_vm_config_tpm_socket' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `gdb`", line: 4, column: 17)', src/main.rs:960:73

---- unit_tests::test_valid_vm_config_vdpa stdout ----
thread 'unit_tests::test_valid_vm_config_vdpa' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `gdb`", line: 7, column: 17)', src/main.rs:960:73

---- unit_tests::test_valid_vm_config_vsock stdout ----
thread 'unit_tests::test_valid_vm_config_vsock' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `gdb`", line: 4, column: 17)', src/main.rs:960:73

failures:
    unit_tests::test_valid_vm_config_cmdline
    unit_tests::test_valid_vm_config_cpus
    unit_tests::test_valid_vm_config_default
    unit_tests::test_valid_vm_config_devices
    unit_tests::test_valid_vm_config_disks
    unit_tests::test_valid_vm_config_fs
    unit_tests::test_valid_vm_config_kernel
    unit_tests::test_valid_vm_config_memory
    unit_tests::test_valid_vm_config_net
    unit_tests::test_valid_vm_config_pmem
    unit_tests::test_valid_vm_config_rng
    unit_tests::test_valid_vm_config_serial_console
    unit_tests::test_valid_vm_config_serial_pty_console_pty
    unit_tests::test_valid_vm_config_tpm_socket
    unit_tests::test_valid_vm_config_vdpa
    unit_tests::test_valid_vm_config_vsock

test result: FAILED. 0 passed; 16 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

Signed-off-by: Alyssa Ross <hi@alyssa.is>
Signed-off-by: Songqian Li <sionli@tencent.com>